name: parts_genie
channels:
  - conda-forge
dependencies:
  - python=3.7
  - cython
  - pandas
  - flask
  - gunicorn
  - bioconda::viennarna
  - sbml2sbol>=0.1.13
  - pip
  - pip:
    - git+https://github.com/nroehner/liv-utils.git